"""Remove genres

Revision ID: 1084ce424a8f
Revises: 20592e20550f
Create Date: 2022-08-21 10:13:00.301243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1084ce424a8f'
down_revision = '20592e20550f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'genres')
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
