"""Add genres

Revision ID: 73bd931664c2
Revises: 1084ce424a8f
Create Date: 2022-08-21 10:13:41.923797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bd931664c2'
down_revision = '1084ce424a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column(
        'genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column(
        'genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###
